### ISSUE TITLE
Sessions expire even with user activity

### ISSUE THREAD

**Issue by Avaq** [Avaq/node-server-skeleton#18]
The only way to extend a session is to refresh the authorization token using a refresh token. However, it is good practice for a client only to store the refresh token if the user opted to be remembered on the client. When the authorization token expires without the client being allowed to refresh it, the session may expire while the user is in the middle of something.

Allowing sessions to be arbitrarily extended using *just* the authorization token is problematic though, as it would defeat the point of not storing refresh tokens.

**Comment by Beanow** [comment]
From my experience the most common cause of security issues is poor client implementations. Simplifying session management for your clients may be a theoretical compromise in attack window and such, but in practice tends to make for the most secure implementations.

The longest lived and easiest to compromise secrets of all are still the username and password, which completely rely on TLS as well to not be compromised. These are much more interesting and viable to attack than randomly generated secrets backed by industry standard crypto.

Therefore I would make heavy assumptions about TLS doing it's job with keeping your secrets secret and preventing the bulk of MITM attacks and session tokens leaking. And implement auth / refresh tokens the way it is least error prone for the majority of clients.

Allowing indefinite extending of sessions using only the auth token in my opinion is a great improvement because this means clients don't need to be smart about their session management.

With that rationale in mind, the refresh token doesn't become useless. It's a simple, not very error prone way to implement "remember me" functionality. It discourages clients to do something really bad like storing the username and password in plain text on disk to achieve the same result.

**Comment by Avaq** [comment]
Several questions that come up:

* If sessions would be capable of extending themselves, perhaps they should be shorter lived (current lifetime defaults to six hours). A typical session usually times out after 15 minutes or so.
* Should a new token(-pair) present itself automatically? Or should the client explicitly refresh it using their auth token. Usually in server-side session management, the session is touched with every request, but I fear with client-side session management this would be subject to concurrency issues.
* When the session is extended, should the server present a whole token pair, or just an auth token? In case of the latter, should the new token share refresh-id with the old, and thus be "refreshable" by the original refresh token?
* Should we allow the session to be extended using an expired auth token? If not; what triggers a client to refresh their token?
* For how long should a token be extendable after it has expired?
* Should we restrict token extension to a single IP address? If not; it would allow anyone getting their hands on a token to post it on twitter, granting everyone access to an account forever. Someone with dynamic IP would have to use "remember me" (the refresh token).

**Comment by Beanow** [comment]
Since this started to smell like reinventing session cookies, I ran into this delightfully compelling rant: http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/

**Comment by Beanow** [comment]
Looking around for some microservice style scaling recommendations, I found that his arguments are usually adopted by delegating this to OpenID Connect / OAuth 2.0 providers. This is by no means a stateless solution since the identity provider is the big ball of state here. Amazon has picked up on this common practice and provides AWS Cognito which does more or less the same thing with a different format for the tokens.

What all of these have in common is:
- Sessions are statefull on the server side, but high-availability configurations are used for scalability.
- Application / resource servers only know how to validate short-lived tokens.
- Log in, log out and "remember me" is handled by the identity provider.
- Providing better UX by transparently replacing expired tokens is done on the client (often using hidden iframes to address the javascript security issues).
- Short lived tokens can be:
  - JWTs that can neither be extended nor revoked
  - Opaque tokens that need to be validated with the identity provider with a s2s request
  - Hybrid style, JWTs for providing claim information, but s2s requests for expiring

**Comment by Avaq** [comment]
More against the use of JWT:

* https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid
* https://auth0.com/blog/critical-vulnerability-in-json-web-encryption/

I will start work on removing it.

**Comment by Avaq** [comment]
How about this:

* Upon authentication, a user is given a JWT pair.
* The authorisation token is stateless and short-lived. It contains everything necessary for the server to perform authorisation without having to contact a database, including the ID of the associated refresh token.
* The refresh token contains an issue date and an ID. The ID corresponds to server state.
* The validity of the refresh token is determined by the server. The server can:
    1. Invalidate a particular refresh token by removing state from the server
    1. Expire refresh tokens by setting a lifetime for their state
    1. Extend the lifetime of a refresh token when it is used to request a new authorisation token

I believe this gives the best from all worlds:

* The authentication servers have low server-load due to stateless authentication tokens. The primary servers can do round-robin load balancing and don't need access to a central piece of state.
* Most of the control is held by the server, as it keeps state about the refresh tokens.
* A "remember me" feature would just increase the TTL of the server-state corresponding to a refresh token.
* User will not be logged-out after an authorisation token expires, because the client can transparently extend their session by requesting a new authorisation token using their refresh token.
* As long as a user keeps using the service, they will not lose their session, because the server keeps touching the state every time a refresh is done.

There is also potential for increased security measurements:

* The authorising server could choose to doubly-verify an authorisation token with the authentication server by asking it if the associated refresh token is still valid, when it deems this necessary.
* The authentication server could track every refresh token it has handed out for a particular user, and from where it's being used to generate new authorisation tokens. It could use this information to become suspicious of certain scenario's, or restrict the amount of active login sessions.

**Comment by Avaq** [comment]
The project has been discontinued. Please refer to [authomatic](https://github.com/wearereasonablepeople/authomatic) for all your jwt-session needs.
